{
 "title": "NetApp HCI - SolidFire Cluster",
 "description": "Metrics for SolidFire cluster",
 "tags": [
  "SolidFire",
  "HCI"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "$cluster", "query": "netapp.solidfire.cluster.*" }
  ]
 },
 "panels": [
  { "title": "SolidFire Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.fault.warning"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.fault.error"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.fault.critical"
    }
   ]
  },
  {
   "title": "Fault History",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(netapp.solidfire.cluster.$Cluster.fault.critical), 'Cluster Critical Faults')"
    },
    {
     "target": "alias(sumSeries(netapp.solidfire.cluster.$Cluster.fault.error), 'Cluster Errors')"
    },
    {
     "target": "alias(sumSeries(netapp.solidfire.cluster.$Cluster.fault.warning), 'Cluster Warnigs')"
    }
   ]
  },
  { "title": "Storage Efficiencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Compression Factor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.compression_factor"
    }
   ]
  },
  {
   "title": "Deduplication Factor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.dedupe_factor"
    }
   ]
  },
  {
   "title": "Thin Provisioning Factor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.thin_factor"
    }
   ]
  },
  {
   "title": "Efficiency Factor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.efficiency_factor"
    }
   ]
  },
  { "title": "Cluster Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readOps), 5), 'Read IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeOps), 5), 'Write IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(sumSeries(netapp.solidfire.cluster.$Cluster.{readOps,writeOps})), 5), 'Total IOPS')"
    }
   ]
  },
  {
   "title": "$Cluster Read/Write Bytes / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readBytes), 5), 'Read Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeBytes), 5), 'Write Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(perSecond(netapp.solidfire.cluster.$Cluster.{readBytes,writeBytes})), 5), 'Total Bytes/s')"
    }
   ]
  },
  {
   "title": "$Cluster Cluster Recent I/O Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(netapp.solidfire.cluster.$Cluster.clusterRecentIOSize, 5), 'I/O Size')"
    }
   ]
  },
  { "title": "Cluster Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$Cluster Cluster Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(netapp.solidfire.cluster.$Cluster.clusterUtilizationScaled, 100)"
    }
   ]
  },
  {
   "title": "$Cluster Utilization Over Time",
   "type": "graph",
   "description": "CPU utilization of all SolidFire nodes in the selected cluster over time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(keepLastValue(netapp.solidfire.cluster.$Cluster.clusterUtilizationScaled, 5), 100), 3)"
    }
   ]
  },
  {
   "title": "$Cluster Node CPU Usage per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.node.*.cpu, 5), 5)"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$Cluster Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.activeSessions, 5), 3)"
    }
   ]
  },
  {
   "title": "$Cluster  Client Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.clientQueueDepth, 5), 3)"
    }
   ]
  },
  {
   "title": "$Cluster Drive Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.*, 5), 6)"
    }
   ]
  }
 ]
}