{
 "title": "NetApp HCI - SolidFire Volume",
 "description": "Volume performance metrics",
 "tags": [
  "SolidFire",
  "HCI"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "AccountID",
    "query": "netapp.solidfire.cluster.$Cluster.accountID.*"
   },
   {
    "name": "Volume",
    "query": "netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.volumeSize"
    }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(scale(#A, 4096), #C)",
     "targetFull": "divideSeries(scale(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.nonZeroBlocks, 4096), netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.volumeSize)"
    }
   ]
  },
  {
   "title": "Performance Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.volumeUtilization"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.throttle)"
    }
   ]
  },
  {
   "title": "%Read",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(divideSeries(#A, #C), 'Pct Read')",
     "targetFull": "alias(divideSeries(aliasByMetric(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readOps), alias(sumSeries(#A, aliasByMetric(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeOps)), 'TotalOps')), 'Pct Read')"
    }
   ]
  },
  {
   "title": "%Write",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(divideSeries(#B, #C), 'Pct Write')"
    }
   ]
  },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readBytes), 'Read')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeBytes), 'Write')"
    }
   ]
  },
  {
   "title": "Volume IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readOps), 'Read')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeOps), 'Write')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.actualIOPS, 'Total')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.averageIOPSize, 'Avg IOP Size')"
    }
   ]
  },
  {
   "title": "Latency & Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readLatencyUSec, 'Read Latency')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeLatencyUSec, 'Write Latency')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.clientQueueDepth, 'Queue Depth')"
    }
   ]
  }
 ]
}