{
 "title": "NetApp HCI - SolidFire Node",
 "description": "Per node statistics for a SolidFire cluster",
 "tags": [
  "SolidFire",
  "HCI"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "Node",
    "query": "netapp.solidfire.cluster.$Cluster.node.*"
   }
  ]
 },
 "panels": [
  { "title": "Current CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "Node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.cpu"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.cpu"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.cpu"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.cpu"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Failed Drives",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "repeat": "Node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.drives.status.failed"
    }
   ]
  },
  {
   "title": "Failed Drives",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.drives.status.failed"
    }
   ]
  },
  {
   "title": "Failed Drives",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.drives.status.failed"
    }
   ]
  },
  {
   "title": "Failed Drives",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.drives.status.failed"
    }
   ]
  },
  {
   "title": "Node Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Node Node IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "repeat": "Node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.readOps), 5), 'Read IOPS')"
      },
      {
       "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.writeOps), 5), 'Write IOPS')"
      },
      {
       "target": "alias(sumSeries(#A,#B),'Total IOPS')",
       "targetFull": "alias(sumSeries(alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.readOps), 5), 'Read IOPS'),alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.writeOps), 5), 'Write IOPS')),'Total IOPS')"
      }
     ]
    }
   ]
  },
  { "title": "Storage Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "repeat": "Node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesOut), 'Out')"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesOut), 'Out')"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesOut), 'Out')"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesOut), 'Out')"
    }
   ]
  },
  { "title": "Management Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "repeat": "Node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesOut), 'Out')"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesOut), 'Out')"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesOut), 'Out')"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesOut), 'Out')"
    }
   ]
  },
  { "title": "Network Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$Node Node Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(netapp.solidfire.cluster.$Cluster.node.$Node.networkUtilizationCluster, 5)"
    }
   ]
  }
 ]
}