{
 "title": "NetApp HCI - vSphere ESXi Metrics",
 "tags": [
  "HCI",
  "ESXi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Host", "query": "vsphere.$vcenter.hostsystem.*" },
   { "name": "vcenter", "query": "vsphere.*" },
   { "name": "TopN", "query": "1,3,6,8" }
  ]
 },
 "panels": [
  { "title": "ESXi CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Host ESXi Average CPU Utilization (Mhz)",
   "type": "graph",
   "description": "Average CPU utilization (Mhz) of ESXi hosts",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPU Mhz" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(vsphere.$vcenter.hostsystem.$Host.cpu.usagemhz.average, $TopN), 3)"
    }
   ]
  },
  {
   "title": "$Host ESXi CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.average, 0.01), $TopN), 3)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "repeat": "Host",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  { "title": "ESXi Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$Host ESXi Active Memory",
   "type": "graph",
   "description": "Active memory per ESXi host",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "deckbytes", "label": "Active Memory" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(vsphere.$vcenter.hostsystem.$Host.mem.active.maximum, $TopN), 3)"
    }
   ]
  },
  {
   "title": "$Host Memory Usage (%)",
   "type": "graph",
   "description": "Percentage of ESXi host memory that has been consumed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(scale(vsphere.$vcenter.hostsystem.$Host.mem.usage.maximum, 0.01), $TopN), 3)"
    }
   ]
  }
 ]
}